# docker-compose.yml
version: '3.8'

services:
  redis:
    image: "redis:7.0-alpine"
    container_name: rate-limiter-redis
    ports:
      - "6379:6379" # Exposes Redis on your local machine's port 6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
