# gateway-service/src/main/resources/application.yml
server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379

rate-limiter:
  requests-per-minute: 10

monitoring-service:
  url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: "health"