# gateway-service/src/main/resources/application.yml
server:
  port: 8080 # The port for our Gateway Service
  forward-headers-strategy: framework # Use Spring's modern handling
  tomcat:
    # This is the crucial security setting
    # It tells Tomcat to only process X-Forwarded-* headers if the request
    # comes from a trusted internal proxy.
    remoteip:
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}
      # Add the IP address or regex for your Nginx/load balancer here.
      # The example above trusts any IP from the 10.0.0.0/8 and 192.168.0.0/16 private networks.
spring:
  application:
    name: gateway-service

  data:
    redis:
      host: localhost
      port: 6379

# Custom application properties
rate-limiter:
  requests-per-minute: 10