server:
  port: 8081 # Port for the monitoring service

spring:
  application:
    name: monitoring-service
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:monitoringdb # In-memory database URL
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Automatically creates/updates the database schema
    show-sql: true # Logs SQL statements, useful for debugging
  # H2 Console Configuration (for easy database inspection)
  h2:
    console:
      enabled: true
      path: /h2-console # Access the console at http://localhost:8081/h2-console

management:
  endpoints:
    web:
      exposure:
        include: "health,info"